### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by kdpan** [GreatChenLab/Deep-B3#1]
It is a great work. But I find that there are total 3821 molecules in B3DB, and the label of 198 molecules is the same as B3DB, and the label of 3623 molecules is different.

您好，我发现在这项工作中的数据集的训练集一共有3821个分子是来源于B3DB数据集，但其只有中有198个分子的标签和B3DB一样，其余3623个分子的标签和B3DB都不一样。这是什么原因？
请问在这项工作中 0 是代表 BBB+ 还是 BBB- ？

**Comment by zdread** [comment]
> 这是一部伟大的作品。但是我发现B3DB一共有3821个分子，198个分子的标签和B3DB一样，3623个分子的标签不一样。
> 
> 您好，发现在这个工作中的集会的集821个成员是我训练的3个B3DB数据集，但只有198个成员的标签和B3DB相同，其他3623个成员的标签和B3DB 0 是代表 BBB+ 还是 BBB- ？

您好，请问你将代码成功复现了吗？

**Comment by TangQiang0701** [comment]
> It is a great work. But I find that there are total 3821 molecules in B3DB, and the label of 198 molecules is the same as B3DB, and the label of 3623 molecules is different.
> 
> 您好，我发现在这项工作中的数据集的训练集一共有3821个分子是来源于B3DB数据集，但其只有中有198个分子的标签和B3DB一样，其余3623个分子的标签和B3DB都不一样。这是什么原因？ 请问在这项工作中 0 是代表 BBB+ 还是 BBB- ？

The details about the dataset please refer to the main text doi:10.1093/bib/bbac357.

**Comment by GaoFMH** [comment]
您好，我在复现的过程中在这个代码“python train.py train --feature train.csv --epoch 50 --bs 64 --vis_out 1 --text_out 1”出现了出现了以下错误，该怎么解决？
Traceback (most recent call last):
  File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 256, in encodes
    return TensorCategory(self.vocab.o2i[o])
KeyError: 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1'

**Comment by TangQiang0701** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    环境配置是否有问题，报错前后信息请贴一下
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/31/2023 10:39
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [GreatChenLab/Deep-B3] About Dataset (Issue #1)
        
      
    
  
  
您好，我在复现的过程中在这个代码“python train.py train --feature train.csv --epoch 50 --bs 64 --vis_out 1 --text_out 1”出现了出现了以下错误，该怎么解决？
Traceback (most recent call last):
File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 256, in encodes
return TensorCategory(self.vocab.o2i[o])
KeyError: 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1'

**Comment by GaoFMH** [comment]
2023-03-31 10:22:51,280 - train.py[line:38] - INFO: deep-b3, set the random seed 2022
2023-03-31 10:22:51,280 - train.py[line:303] - INFO: begin training a new deep-b3 model
2023-03-31 10:22:51,280 - train.py[line:304] - INFO: vision outputs feature is 1
2023-03-31 10:22:51,280 - train.py[line:305] - INFO: text outputs feature is 1
2023-03-31 10:22:51,281 - train.py[line:306] - INFO: batch size is 64
2023-03-31 10:22:51,281 - train.py[line:307] - INFO: including image features ? [True]
2023-03-31 10:22:51,281 - train.py[line:308] - INFO: including tabular features ? [True]
2023-03-31 10:22:51,281 - train.py[line:309] - INFO: including text features ? [True]
2023-03-31 10:22:51,291 - train.py[line:319] - INFO: nlp lm data file not exists, begin training nlp model
Traceback (most recent call last):
  File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 256, in encodes
    return TensorCategory(self.vocab.o2i[o])
KeyError: 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\Jupyter Notebook\Deep-B3\DEEP-3\train.py", line 320, in <module>
    pretrain_nlp(train_df)
  File "D:\software\Jupyter Notebook\Deep-B3\DEEP-3\train.py", line 66, in pretrain_nlp
    data_lm = (TextDataLoaders.from_df(
  File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 275, in from_df
    return cls.from_dblock(dblock, df, path=path, seq_len=seq_len, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 192, in from_dblock
    return dblock.dataloaders(source, path=path, bs=bs, val_bs=val_bs, shuffle=shuffle, device=device, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\block.py", line 115, in dataloaders
    return dsets.dataloaders(path=path, after_item=self.item_tfms, after_batch=self.batch_tfms, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 233, in dataloaders
    dls = [dl] + [dl.new(self.subset(i), **merge(kwargs,def_kwargs,val_kwargs,dl_kwargs[i]))
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 233, in <listcomp>
    dls = [dl] + [dl.new(self.subset(i), **merge(kwargs,def_kwargs,val_kwargs,dl_kwargs[i]))
  File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 216, in new
    return super().new(dataset=dataset, res=res, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 63, in new
    res = super().new(dataset, cls, do_setup=False, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 128, in new
    return cls(**merge(cur_kwargs, kwargs))
  File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 189, in __init__
    self.res = [self.sort_func(self.do_item(i)) for i in range_of(self.dataset)] if res is None else res
  File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 189, in <listcomp>
    self.res = [self.sort_func(self.do_item(i)) for i in range_of(self.dataset)] if res is None else res
  File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 133, in do_item
    try: return self.after_item(self.create_item(s))
  File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 140, in create_item
    if self.indexed: return self.dataset[s or 0]
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 332, in __getitem__
    res = tuple([tl[it] for tl in self.tls])
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 332, in <listcomp>
    res = tuple([tl[it] for tl in self.tls])
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 298, in __getitem__
    return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 260, in _after_item
    def _after_item(self, o): return self.tfms(o)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 200, in __call__
    def __call__(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 150, in compose_tfms
    x = f(x, **kwargs)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 73, in __call__
    def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 83, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 89, in _do_call
    return retain_type(f(x, **kwargs), x, ret)
  File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\dispatch.py", line 118, in __call__
    return f(*args, **kwargs)
  File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 258, in encodes
    raise KeyError(f"Label '{o}' was not included in the training dataset") from e
KeyError: "Label 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1' was not included in the training dataset"
这是全部内容

**Comment by TangQiang0701** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        KeyError: "Label 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1' was not included in the training dataset"你是用的自己的数据？还是github提供的数据，或者有修改过数据？检查下数据问题，这个格式的数据是有问题的，SMILES中应该不存在空格。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/31/2023 16:10
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [GreatChenLab/Deep-B3] About Dataset (Issue #1)
        
      
    
  
  
2023-03-31 10:22:51,280 - train.py[line:38] - INFO: deep-b3, set the random seed 2022
2023-03-31 10:22:51,280 - train.py[line:303] - INFO: begin training a new deep-b3 model
2023-03-31 10:22:51,280 - train.py[line:304] - INFO: vision outputs feature is 1
2023-03-31 10:22:51,280 - train.py[line:305] - INFO: text outputs feature is 1
2023-03-31 10:22:51,281 - train.py[line:306] - INFO: batch size is 64
2023-03-31 10:22:51,281 - train.py[line:307] - INFO: including image features ? [True]
2023-03-31 10:22:51,281 - train.py[line:308] - INFO: including tabular features ? [True]
2023-03-31 10:22:51,281 - train.py[line:309] - INFO: including text features ? [True]
2023-03-31 10:22:51,291 - train.py[line:319] - INFO: nlp lm data file not exists, begin training nlp model
Traceback (most recent call last):
File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 256, in encodes
return TensorCategory(self.vocab.o2i[o])
KeyError: 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "D:\software\Jupyter Notebook\Deep-B3\DEEP-3\train.py", line 320, in 
pretrain_nlp(train_df)
File "D:\software\Jupyter Notebook\Deep-B3\DEEP-3\train.py", line 66, in pretrain_nlp
data_lm = (TextDataLoaders.from_df(
File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 275, in from_df
return cls.from_dblock(dblock, df, path=path, seq_len=seq_len, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 192, in from_dblock
return dblock.dataloaders(source, path=path, bs=bs, val_bs=val_bs, shuffle=shuffle, device=device, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\block.py", line 115, in dataloaders
return dsets.dataloaders(path=path, after_item=self.item_tfms, after_batch=self.batch_tfms, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 233, in dataloaders
dls = [dl] + [dl.new(self.subset(i), **merge(kwargs,def_kwargs,val_kwargs,dl_kwargs[i]))
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 233, in 
dls = [dl] + [dl.new(self.subset(i), **merge(kwargs,def_kwargs,val_kwargs,dl_kwargs[i]))
File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 216, in new
return super().new(dataset=dataset, res=res, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 63, in new
res = super().new(dataset, cls, do_setup=False, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 128, in new
return cls(**merge(cur_kwargs, kwargs))
File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 189, in init
self.res = [self.sort_func(self.do_item(i)) for i in range_of(self.dataset)] if res is None else res
File "D:\software\miniconda3\lib\site-packages\fastai\text\data.py", line 189, in 
self.res = [self.sort_func(self.do_item(i)) for i in range_of(self.dataset)] if res is None else res
File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 133, in do_item
try: return self.after_item(self.create_item(s))
File "D:\software\miniconda3\lib\site-packages\fastai\data\load.py", line 140, in create_item
if self.indexed: return self.dataset[s or 0]
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 332, in getitem
res = tuple([tl[it] for tl in self.tls])
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 332, in 
res = tuple([tl[it] for tl in self.tls])
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 298, in getitem
return self._after_item(res) if is_indexer(idx) else res.map(self._after_item)
File "D:\software\miniconda3\lib\site-packages\fastai\data\core.py", line 260, in _after_item
def _after_item(self, o): return self.tfms(o)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 200, in call
def call(self, o): return compose_tfms(o, tfms=self.fs, split_idx=self.split_idx)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 150, in compose_tfms
x = f(x, **kwargs)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 73, in call
def call(self, x, **kwargs): return self._call('encodes', x, **kwargs)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 83, in _call
return self._do_call(getattr(self, fn), x, **kwargs)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\transform.py", line 89, in _do_call
return retain_type(f(x, **kwargs), x, ret)
File "C:\Users\jcbi\AppData\Roaming\Python\Python39\site-packages\fastcore\dispatch.py", line 118, in call
return f(*args, **kwargs)
File "D:\software\miniconda3\lib\site-packages\fastai\data\transforms.py", line 258, in encodes
raise KeyError(f"Label '{o}' was not included in the training dataset") from e
KeyError: "Label 'C C ( C ) N [ C @ H ] 1 C 2 C C C ( C C 2 ) [ C @ @ ] 1 ( O ) c 1 c c c ( C l ) c ( C l ) c 1' was not included in the training dataset"
这是全部内容

**Comment by GaoFMH** [comment]
源数据我用的是github提供的，不过我在train.py和model.py里的代码一部分做了更改，这是因为一些类不兼容的问题，有可能问题处在这里面吗？

这是修改前总是报出的部分错误：
Traceback (most recent call last):
  File "D:\software\Jupyter Notebook\Deep-B3\Deep-B3-\trainnn.py", line 4, in <module>
    from fastai.callbacks import *
ModuleNotFoundError: No module named 'fastai.callbacks'
或者
 'File "D:\software\Jupyter Notebook\Deep-B3\Deep-B3-\trainn.py", line 65, in pretrain_nlp
    data_lm = (TextList.from_df(
NameError: name 'TextList' is not defined

这是我的一些软件版本：
python:3.9.16
torch ：1.10.0+cu113
fastai：2.5.2

**Comment by GaoFMH** [comment]
更改后的train.py 和 model.py 文件放在了我的DEEP_B3库里面
