### ISSUE TITLE
i have configed the environment, but the model can't be trained, i don't know why,

### ISSUE THREAD

**Issue by songyu2022** [GreatChenLab/Deep-B3#2]
python train.py train --feature train_feature.csv --epoch 50 --bs 64 
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from fastai.text import *
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/__init__.py", line 3, in <module>
    from .learner import *
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/learner.py", line 11, in <module>
    from .models import *
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/models/__init__.py", line 1, in <module>
    from .awd_lstm import *
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/models/awd_lstm.py", line 6, in <module>
    from ..data import TextClasDataBunch
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/data.py", line 3, in <module>
    from .transform import *
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/transform.py", line 4, in <module>
    import spacy
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/__init__.py", line 11, in <module>
    from .callbacks import create_copy_from_base_model  # noqa: F401
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/callbacks.py", line 3, in <module>
    from ..language import Language
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/language.py", line 25, in <module>
    from .training.initialize import init_vocab, init_tok2vec
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/initialize.py", line 14, in <module>
    from .pretrain import get_tok2vec_ref
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/pretrain.py", line 16, in <module>
    from ..schemas import ConfigSchemaPretrain
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/schemas.py", line 216, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by songyu2022** [comment]
>>> import fastai,torch,torchvision,pandas,numpy,rdkit
>>> print(fastai.__version__,torch.__version__,torchvision.__version__)
1.0.61 1.9.0 0.10.0a0
>>> print(pandas.__version__,numpy.__version__,rdkit.__version__)
1.4.2 1.22.3 2020.09.1
these are version of my softwares

**Comment by TangQiang0701** [comment]
> python train.py train --feature train_feature.csv --epoch 50 --bs 64 Traceback (most recent call last): File "train.py", line 3, in from fastai.text import * File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/**init**.py", line 3, in from .learner import * File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/learner.py", line 11, in from .models import * File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/models/**init**.py", line 1, in from .awd_lstm import * File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/models/awd_lstm.py", line 6, in from ..data import TextClasDataBunch File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/data.py", line 3, in from .transform import * File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/fastai/text/transform.py", line 4, in import spacy File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/**init**.py", line 14, in from . import pipeline # noqa: F401 File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/pipeline/**init**.py", line 1, in from .attributeruler import AttributeRuler File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in from .pipe import Pipe File "spacy/pipeline/pipe.pyx", line 8, in init spacy.pipeline.pipe File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/**init**.py", line 11, in from .callbacks import create_copy_from_base_model # noqa: F401 File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/callbacks.py", line 3, in from ..language import Language File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/language.py", line 25, in from .training.initialize import init_vocab, init_tok2vec File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/initialize.py", line 14, in from .pretrain import get_tok2vec_ref File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/training/pretrain.py", line 16, in from ..schemas import ConfigSchemaPretrain File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/site-packages/spacy/schemas.py", line 216, in class TokenPattern(BaseModel): File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.**new** File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.**init** File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare File "pydantic/fields.py", line 545, in pydantic.fields.ModelField._type_analysis File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis File "/data/songyu/softwareInstall/Anaconda3/envs/Deep-B3/lib/python3.8/typing.py", line 774, in **subclasscheck** return issubclass(cls, self.**origin**) TypeError: issubclass() arg 1 must be a class

It looks like there's a conflict between the version of pydantic and spacy.

**Comment by songyu2022** [comment]
> 

i installed them by default, so what're the right version about two packages?
