### ISSUE TITLE
NameError: name 'LearnerCallback' is not defined

### ISSUE THREAD

**Issue by sumone-compbio** [GreatChenLab/Deep-B3#3]
Hi, I need help in fixing this error please. 

`Traceback (most recent call last):
  File "/home/sumit/DEEPB3/train.py", line 15, in <module>
    import model
  File "/home/sumit/DEEPB3/model.py", line 149, in <module>
    class RNNTrainerSimple(LearnerCallback):
NameError: name 'LearnerCallback' is not defined
`

**Comment by BioTKang** [comment]
Please check the version of the installed package

**Comment by TangQiang0701** [comment]
> Hi, I need help in fixing this error please.
> 
> `Traceback (most recent call last): File "/home/sumit/DEEPB3/train.py", line 15, in <module> import model File "/home/sumit/DEEPB3/model.py", line 149, in <module> class RNNTrainerSimple(LearnerCallback): NameError: name 'LearnerCallback' is not defined `

Please check the version of the installed package

**Comment by sumone-compbio** [comment]
Hi @BioTKang, thank you so much for the response. Below are the versions of the installed packages:
fastai                    2.7.13                     
fastcore                  1.5.29                     
fastdownload              0.0.7                      
fastprogress              1.0.3

**Comment by sumone-compbio** [comment]
I apologise for not checking the required versions. Thank you, I'll clean the working environment and re-run the process.

**Comment by sumone-compbio** [comment]
@BioTKang one more question please, what should be the value of n and m in:
`train.py train --feature train.csv --epoch 50 --bs 64 --vis_out n --text_out m` Is it just the number of molecule images and SMILES for my dataset?

**Comment by sumone-compbio** [comment]
Hi, I got this error now even though I'm using the appropriate version of fastai = 1.0.61.
`Traceback (most recent call last):                                                                                                     
  File "train.py", line 319, in <module>
    pretrain_nlp(train_df)
  File "train.py", line 73, in pretrain_nlp
    EarlyStoppingCallback(learn, min_delta=1e-5, patience=4),
NameError: name 'EarlyStoppingCallback' is not defined
`
